### ISSUE TITLE
Moving platforms

### ISSUE THREAD

**Issue by indietimmie** [ssjtroly/smb3-nes-web-randomizer#1]
Hello! I love your recreation of the MB3 randomizer, works great. Idk if you've noticed or if you have been told (I apologize if so) With randomize enemies on, the floating platforms in levels aren't there. Only real issue I've run into atm.

**Comment by ssjtroly** [comment]
thanks for letting me know, i didnt notice. should be fixed now.
im sure there are alot of other problems with the enemy randomizer, i cant guarantee its even completable right now but its good to post any problems with it.
