### ISSUE TITLE
Item block shuffle softlock on vanilla 7-7

### ISSUE THREAD

**Issue by pkmnfrk** [ssjtroly/smb3-nes-web-randomizer#2]
Settings: MTEzMjYzNzA5IDA=
Seed: 2689814487
Level: Shuffled 2-1 (vanilla 7-7)

The gimmick of this level is that you need a star to get across the expanse of nippers, but you get a coin instead. I imagine that a P-Wing could get across, but you don't get one either (also, that's unreliable).

**Comment by ssjtroly** [comment]
fixed this by just excluding 7-7 from item block randomization
