### ISSUE TITLE
Enemy shuffle softlock on vanilla 8-1

### ISSUE THREAD

**Issue by pkmnfrk** [ssjtroly/smb3-nes-web-randomizer#3]
Settings: MTEzMjYzNzA5IDA=
Seed: 2689814487
Level: Shuffled 1-9 (vanilla 8-1)

About 2/3 into the level, there is a section of Bullet Bill launchers over pits (a short one on the left, a tall one on the right). Crossing this pit is either incredibly difficult or impossible as you get no powerups in that level. And, even if you did, the spinning discs that the Bills got replaced with are a real pain.

I only got across because I got a Leaf earlier, and a lot of save scumming.

**Comment by ssjtroly** [comment]
i wouldnt really call this a softlock since it is possible to make it through without any powerups but it is incredibly hard.
i excluded enemy spawners from enemies that are randomized, but there is no guarantee that will always make it easier.

**Comment by pkmnfrk** [comment]
I won't disagree that it might be technically possible if hard, but I think having the bullet bills there will already be a huge help. Thanks!
